services:
  - type: web
    name: climate-risk-dashboard
    env: docker  # Use Docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
